---

name: secureclip CI/CD

on: 
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    types: [opened, synchronize, reopened]


jobs:

  build:

    runs-on: optibrium-k8s-cluster
    if: ${{ github.actor != 'dependabot[bot]' }}
    timeout-minutes: 20
    steps:

      - name: checkout
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Collect build tag
        run: |
          if echo "${{ github.ref }}" | grep -q "^refs/tags/v[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
            echo "BUILD_TAG=$(echo "${{ github.ref }}" | sed 's|^refs/tags/v||')" >> $GITHUB_ENV
          else
            echo "BUILD_TAG=$(date +%Y%m%d.%s.000000)" >> $GITHUB_ENV
          fi

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.OPTIBRIUMBOT_AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.OPTIBRIUMBOT_AWS_SECRET_ACCESS_KEY  }}
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.OPTIBRIUM_INFRA_ACCOUNT_ID }}:role/AWSControlTowerExecution
          role-skip-session-tagging: true
          role-duration-seconds: 900

      - name: Set AWS CodeArtifact credentials
        run: |
         token=$(aws codeartifact get-authorization-token --domain pypi --domain-owner $OPTIBRIUM_INFRA_ACCOUNT_ID --query authorizationToken --output text)
         echo "PIP_EXTRA_INDEX_URL=https://aws:$token@pypi-$OPTIBRIUM_INFRA_ACCOUNT_ID.d.codeartifact.eu-west-2.amazonaws.com/pypi/pypi-infra/simple" >> $GITHUB_ENV
        env:
         OPTIBRIUM_INFRA_ACCOUNT_ID: "${{ secrets.OPTIBRIUM_INFRA_ACCOUNT_ID }}"

      - name: install wheel
        run: 'pip3 install wheel'

      - name: build wheel
        run: 'python3 setup.py bdist_wheel'
      
      - name: upload to PyPi
        run: |
            aws codeartifact login --tool twine --repository pypi-infra --domain pypi --domain-owner $OPTIBRIUM_INFRA_ACCOUNT_ID &&
            twine upload --skip-existing --repository codeartifact dist/*.whl
        env:
          OPTIBRIUM_INFRA_ACCOUNT_ID: "${{ secrets.OPTIBRIUM_INFRA_ACCOUNT_ID }}"
     
      - name: Login to AWS ECR
        run: "aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin ${{ secrets.OPTIBRIUM_INFRA_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com"

      - name: Release build
        id: release_build
        uses: docker/build-push-action@v6
        with:
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.OPTIBRIUM_INFRA_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/secureclip:${{ env.BUILD_TAG }}
          build-args: |
            PIP_EXTRA_INDEX_URL=${{ env.PIP_EXTRA_INDEX_URL }}
            BUILD_TAG=${{ env.BUILD_TAG }}
          provenance: false
